version: "3.9"

services:
  postgresql:
    image: postgres:14
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpwd
      - POSTGRES_DB=scrapper
    ports:
      - "5432:5432"
    volumes:
      - ./migrations/pg-data:/var/lib/postgresql/data/
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 7s
      timeout: 10s
      retries: 120
    networks:
      - backend

  liquibase-migrations:
    image: liquibase/liquibase:4.18
    depends_on:
      postgresql:
        condition: service_healthy
    command:
      - --hub-mode=off
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/scrapper
      - --username=pguser
      - --password=pgpwd
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - backend
networks:
  backend: